# Site settings
title: neiro λ Web development, functional programming
name: neiro λ Web development, functional programming
author: "Alexey Kuznetsov"
email: "mailto:neiro.mail@gmail.com"
description: >
  My personal website, blog and portfolio
baseurl: ""
url: "http://neiro.io"
source_url: "https://github.com/ne1ro/neiro.io"
github: "https://github.com/ne1ro"
linkedin: "https://linkedin.com/in/neiro"
salam: "https://salam.io/neiro"
timezone: Europe/Moscow
markdown: kramdown
highlighter: rouge
assets:
  source_maps: true
  destination: "/assets"
  gzip: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
# jekyll-crosspost_to_medium:
#   enabled: true
#   status: draft

exclude:
  - bower.json
  - LICENSE
  - Gemfile
  - Guardile
  - Gemfile.lock
  - vendor
  - readme.md
  - Capfile
  - config

navigation:
  - title: Blog
    url: /
  - title: Projects
    url: /projects
  - title: About me
    url: /about
  - title: Contact
    url: /contact

kramdown:
  input: GFM
  syntax_highlighter: rouge

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

assets:
  js_compressor: uglifier
  css_compressor: sass
  gzip: [ text/css, application/javascript, image/jpeg, image/png ]

plugins:
  - jekyll-time-to-read
  - jekyll-assets
